// Builds public/track2.html from page.template.html + items.json.
// The template embeds the item/scoring data at __ITEMS_JSON__ (a <script
// type="application/json">), so the page is fully self-contained and the
// same data file is the single source of truth for later server-side scoring.
//   run:  node track2/build.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const tpl = fs.readFileSync(path.join(dir, 'page.template.html'), 'utf8');
const data = JSON.parse(fs.readFileSync(path.join(dir, 'items.json'), 'utf8'));
const js = JSON.stringify(data).replace(/<\//g, '<\\/');
const out = tpl.replace('__ITEMS_JSON__', js);
const dest = path.join(dir, '..', 'public', 'track2.html');
fs.writeFileSync(dest, out);
console.log(`built ${dest} (${data.items.length} items, ${out.length} bytes)`);

// Emit the same data as an importable server module so the submit/scoring
// endpoints recompute from the exact same single source of truth as the page.
const serverModule = `// AUTO-GENERATED by track2/build.mjs from track2/items.json — do not edit.\nexport const TRACK2_DATA = ${js};\n`;
const serverDest = path.join(dir, '..', 'api', '_track2-data.js');
fs.writeFileSync(serverDest, serverModule);
console.log(`built ${serverDest}`);
