-- Track 1 (Verification by Origin) application intake.
-- Written only by serverless functions using the service role key.
-- Documents live in the private 'applicant-documents' storage bucket
-- (created via the Storage API; buckets are not schema objects).

create table if not exists public.applications (
  id uuid primary key default gen_random_uuid(),
  file_number bigint generated by default as identity,
  created_at timestamptz not null default now(),
  submitted_at timestamptz,
  -- 'draft' until the browser confirms every document uploaded; drafts that
  -- never finalize are inert rows with no readable documents.
  status text not null default 'draft' check (status in ('draft','submitted')),
  full_name text not null,
  email text not null,
  phone text,
  high_school text not null,
  origin_kind text not null check (origin_kind in ('birth_certificate','school_enrollment')),
  -- Determination fields are set later by the reviewer (admin build step).
  determination text check (determination in ('verified','denied','returned_for_insufficient_suffering')),
  determined_at timestamptz,
  determination_notes text
);

create table if not exists public.application_documents (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references public.applications(id) on delete cascade,
  kind text not null check (kind in ('high_school_record','origin_document')),
  storage_path text not null unique,
  original_filename text not null,
  mime_type text not null,
  size_bytes bigint not null,
  uploaded boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists application_documents_application_idx
  on public.application_documents (application_id);

-- RLS on with NO policies: anon/authenticated can neither read nor write.
-- Only the service role (server-side) touches these tables.
alter table public.applications enable row level security;
alter table public.application_documents enable row level security;

revoke all on public.applications from anon, authenticated;
revoke all on public.application_documents from anon, authenticated;
