-- Track 2 (Verification by Experience) intake + scoring.
-- Fully separate from Track 1's public.applications — additive, no change to
-- existing tables. Written only by serverless functions using the service role.
-- The only uploaded document is a headshot (for the ID card); Track 2 is
-- otherwise honor-system (no evidence documents).

create table if not exists public.track2_applications (
  id uuid primary key default gen_random_uuid(),
  file_number bigint generated by default as identity,
  created_at timestamptz not null default now(),
  submitted_at timestamptz,
  status text not null default 'draft' check (status in ('draft','submitted')),

  full_name text not null,
  given_names text not null,
  surname text not null,
  borough text not null check (borough in ('manhattan','brooklyn','queens','bronx','staten_island')),
  email text not null,
  phone text,
  date_of_birth date not null,

  -- free-text questions (same as Track 1; not scored by the instrument)
  best_pizza text,
  worst_subway_station text,
  ny_story text,
  comments text,

  -- raw item answers: { itemId: true } for checkbox/trap/flag, { itemId: <int> } for counters
  responses jsonb not null default '{}'::jsonb,

  -- authoritative score, recomputed server-side at submit (never trusted from client)
  score integer,
  suffering_total integer,
  tenure_contribution integer,
  soft_counted integer,
  gates jsonb,
  provisional_determination text check (provisional_determination in
    ('verified','denied','returned_for_insufficient_suffering','disqualified')),

  -- reviewer determination
  determination text check (determination in
    ('verified','denied','returned_for_insufficient_suffering','disqualified')),
  determined_at timestamptz,
  determination_notes text,

  -- issuance
  id_number text,
  id_card_token text
);

create unique index if not exists track2_id_card_token_key
  on public.track2_applications (id_card_token) where id_card_token is not null;
create unique index if not exists track2_id_number_key
  on public.track2_applications (id_number) where id_number is not null;

create table if not exists public.track2_documents (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references public.track2_applications(id) on delete cascade,
  kind text not null check (kind in ('headshot')),
  storage_path text not null unique,
  original_filename text not null,
  mime_type text not null,
  size_bytes bigint not null,
  uploaded boolean not null default false,
  purged_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists track2_documents_application_idx
  on public.track2_documents (application_id);

-- RLS on with no policies: only the service role (server-side) can touch these.
alter table public.track2_applications enable row level security;
alter table public.track2_documents enable row level security;
revoke all on public.track2_applications from anon, authenticated;
revoke all on public.track2_documents from anon, authenticated;
